### ISSUE TITLE
NameError: name 'plutil' is not defined

### ISSUE THREAD

**Issue by yhJang94** [QhelDIV/ShapeFormer#19]
how can i solve this problem?

(shapeformer) yohan@server10:/data/yohan/ShapeFormer$   python -m shapeformer.trainer --opts configs/demo/demo_vqdif.yaml --gpu 0 --mode "run"
**** INFO **** Choosing GPUS: [0]
**** INFO **** Resetting GPUS ids to: [0]
**** INFO **** Running single opt file
Global seed set to 314
Traceback (most recent call last):
  File "/home/yohan/.conda/envs/shapeformer/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/yohan/.conda/envs/shapeformer/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/yohan/ShapeFormer/shapeformer/trainer.py", line 353, in <module>
    trainer = Trainer(parsed.opts[0], mode='train', gpus=gpus)
  File "/data/yohan/ShapeFormer/shapeformer/trainer.py", line 61, in __init__
    self.load_model()
  File "/data/yohan/ShapeFormer/shapeformer/trainer.py", line 124, in load_model
    self.model = sysutil.instantiate_from_opt(self.opt.pl_model_opt)
  File "/data/yohan/ShapeFormer/xgutils/sysutil.py", line 279, in instantiate_from_opt
    return load_object(opt["class"])(**opt.get("kwargs", dict()))
  File "/data/yohan/ShapeFormer/xgutils/sysutil.py", line 273, in load_object
    return load_module_object(module_path, object_name)
  File "/data/yohan/ShapeFormer/xgutils/sysutil.py", line 255, in load_module_object
    modulelib = importlib.import_module(module_path)
  File "/home/yohan/.conda/envs/shapeformer/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/data/yohan/ShapeFormer/shapeformer/models/vqdif/vqdif.py", line 170, in <module>
    class VisRecon3D(plutil.VisCallback):
NameError: name 'plutil' is not defined

**Comment by QhelDIV** [comment]
It turns out this is due to the fact you are using a newer version of the xgutils library, where you can not import the utils by just `from xgutils import *`.

To resolve this problem, you can simply using the xgutils at version `b549310`, (which is also the commit number of branch 'shapeformer').
I have updated this repo, when you `git clone --recursive git@github.com:QhelDIV/ShapeFormer.git` you should automatically get the right version of xgutils.

Hope this method works for you. If not so, feel free to put more information here.
