### ISSUE TITLE
Problem about Multi-gpu Training Vqdif 

### ISSUE THREAD

**Issue by yixuanli1230** [QhelDIV/ShapeFormer#20]
I hope you're doing well. I encountered an error while executing the following command in VS Code:

python -m shapeformer.trainer --opts configs/vqdif/shapenet_res16.yaml --gpu 0 1 2 3 4. 

However, I received the following traceback:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/xx/anaconda3/envs/shapeformer/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/home/xx/anaconda3/envs/shapeformer/lib/python3.7/multiprocessing/spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
_pickle.UnpicklingError: state is not a dictionary

This error seems to be related to inter-process communication when using multiple GPUs. The state information is not being properly serialized and transferred between processes. Do you have any insights or suggestions on how to resolve this issue? Thanks!

**Comment by kajalsanklecha** [comment]
Hello @yixuanli1230 , I am facing the same issue, did you find a solution to this issue?
